swagger: "2.0"
info:
  description: VideoDroid API
  version: "1.0.0"
  title: VideoDroid API
consumes:
  - application/json
produces:
  - application/json

basePath: /droid

# Paths supported by the server application
paths:
  /range:
    get:
      operationId: droid.range
      tags:
        - Range
      summary: Read distance
      description: Read distance and ranging settings
      responses:
        200:
          description: Successfully read ranging
          schema:
            properties:
              distance:
                type: integer
              mode:
                type: string

    put:
      operationId: droid.rangemode
      tags:
        - Range
      summary: Set the ranging mode
      description: Set to low, medium or high
      parameters:
        - name: put
          in: body
          required: True
          schema:
            type: object
            properties:
              mode:
                type: string

      responses:
        200:
          description: Successful update of range mode
        404:
          description: Invalid mode

  /battery:
    get:
      operationId: droid.battery
      tags:
        - Battery
      summary: Get the battery level
      description: Get the battery level as a percentage value
      responses:
        200:
          description: Percentage battery level
          schema:
            properties:
              charge:
                type: integer
        503:
          description: Charge information unavailable

  /move:
    put:
      operationId: droid.move
      tags:
        - Move
      summary: Move the droid
      description: Issues commands to each drive wheel
      parameters:
        - name: put
          in: body
          required: True
          schema:
            type: object
            properties:
              command:
                type: string
              speed:
                type: integer
      responses:
        200:
          description: Successful move command
        500:
          description: Cannot issue move commands
    get:
      operationId: droid.getmove
      tags:
        - Move
      summary: Get the last move from the droid
      responses:
        200:
          description: Last move command issued
          schema:
            properties:
              command:
                type: string
              speed:
                type: integer
        500:
          description: Cannot issue move commands

  /lights:
    put:
      operationId: droid.leds
      tags:
        - Lights
      summary: Control the droid lights
      description: Turn on and off the lights on droid
      parameters:
        - name: put
          in: body
          required: True
          schema:
            type: object
            properties:
              turnon:
                type: integer
      responses:
        200:
          description: Light change successful
